#_ CORE _#
java.library.path: "/usr/local/lib:/opt/local/lib:/usr/lib"
storm.local.dir: "/usr/lib/storm/storm-local"
storm.cluster.mode: "distributed"
storm.local.mode.zmq: false
storm.home: "/usr/lib/storm"

#_ ZOOKEEPER _#
storm.zookeeper.servers:
    - "localhost"
storm.zookeeper.port: 2181
storm.zookeeper.root: "/storm"
storm.zookeeper.session.timeout: 20000
storm.zookeeper.retry.times: 5
storm.zookeeper.retry.interval: 1000
dev.zookeeper.path: "/tmp/dev-storm-zookeeper"

#_ WORKER _#
worker.childopts: "-Xmx768m"
worker.heartbeat.frequency.secs: 1
task.heartbeat.frequency.secs: 3
task.refresh.poll.secs: 10


#_ TOPOLOGY _#
topology.debug: false
topology.optimize: true
topology.workers: 1
topology.ackers: 1
topology.message.timeout.secs: 30
topology.skip.missing.kryo.registrations: false
topology.max.task.parallelism: null
topology.max.spout.pending: null
topology.state.synchronization.timeout.secs: 60
topology.stats.sample.rate: 0.05
topology.fall.back.on.java.serialization: true
topology.worker.childopts: null

#_ Mesos _#
mesos.master.url: "zk://127.0.0.1:2181/mesos"
mesos.framework.role: "*"
mesos.framework.checkpoint: false


# Use Netty to avoid ZMQ dependencies
storm.messaging.transport: "backtype.storm.messaging.netty.Context"
